### ISSUE TITLE
Architect cannot find matrices that are stored in hd5 format. 

### ISSUE THREAD

**Issue by avishekrk** [dssg/architect#38]
After switching matrices from csv to hd5. When running an experiment architect could not find any matrices. Looks like it is hardcoded to look for csv(s) and not matrices stored in hd5.

**Comment by thcrock** [comment]
Yeah a couple things need to happen.  Here is an issue I created a while ago for tracking the implementation of hdf5 in architect (ie, building hdf matrices instead of the CSV implementation that's hardcoded).

https://github.com/dssg/architect/issues/18

In addition, we will need to implement a storage wrapper in catwalk similar to the MettaCSVMatrixStore that can be used in experiments. I created an issue for that here: https://github.com/dssg/catwalk/issues/17

**Comment by jesteria** [comment]
This issue was moved to dssg/triage#280
